### PR TITLE
Decode morse code

### PR DESCRIPTION
**Pull request by baqar-abbas**
### Decode a morse code 
    

-     Created a Class and defined MORSE_CODE hash
-     Created a method to decode a Morse code character
-     Created a method to decode an entire word in Morse code
-     Create a method to decode the entire message in Morse code

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
Hi Team , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] Kindly update your readme file with relevant project details  for documentation purposes

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by baqar-abbas** [comment]
Readme file has been created and updated as suggested by the code Reviewer

**Review by uwadonat — APPROVED** [review]
## Hi @Team,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 
### Highlights
- No linter errors ✔️
- Well-organized project and documented project ✔️
- Professional readme file ✔️
- Detailed pull request message ✔️

# Status: Approved ✔️✔️✔️

209362895-9762f2f8-13cf-4ce0-90b6-a672c4f04196


## Optional suggestions
- [x] Kindly add the correct link to your live demo in Readme. Currently, you are referring to another project.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

**Comment by baqar-abbas** [comment]
Thanks @uwadonat :)

**Pull request merged**
